Base Classes
Red-Ovenbirds/taipa-builder pull request #23
Opened 2019-10-08 15:55 UTC by Jagni

Container, Clayblock e TextClayblock

Criação de projeto para executar e fazer testes na pasta development_app

Fixes #6 #7 #12

2019-10-09 13:12 UTC, RegisMelgaco requested changes
Tem só que tirar os comentários padrão do Flutter. E tem a sugestão de usar os testes de widget do flutter, vale muito a pena. 

https://flutter.dev/docs/cookbook/testing/widget/introduction

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/README.md
> +samples, guidance on mobile development, and a full API reference.
Arruma ou tira esse reame

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/lib/main.dart
> +        // is not restarted.
Comentário que não agrega

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/lib/main.dart
> +          // the App.build method, and use it to set our appbar title.
Não agrega

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/lib/main.dart
> +                    "Oi som teste askdnajks dkjna sdkjnasd kjansd aksjdna dskjansdjknaskjdna sdkansd aksjdna sdkjansdjknasd asdkjnasd"),
Dá uma olhadinha nos testes automáticos de widgets. Achei mega easy e vou utilizar no app de olho.

olha aqui: https://flutter.dev/docs/cookbook/testing/widget/introduction

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/pubspec.yaml
> +# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
Não agrega

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/pubspec.yaml
> +  # Use with the CupertinoIcons class for iOS style icons.
Não agrega.

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/pubspec.yaml
> +# following page: https://dart.dev/tools/pub/pubspec
Não agrega.

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/pubspec.yaml
> +# The following section is specific to Flutter.
Não agrega.

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/pubspec.yaml
> +  # the material Icons class.
Não agrega.

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/pubspec.yaml
> +  # see https://flutter.dev/custom-fonts/#from-packages
Não agrega.

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/test/widget_test.dart
> +// tree, read text, and verify that the values of widget properties are correct.
Não agrega.

2019-10-09 13:12 UTC, RegisMelgaco commented on development_app/test/widget_test.dart
> +  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
Arruma os testes de widget é muito top e easy.

2019-10-09 13:12 UTC, RegisMelgaco commented on examples/instantiation.dart
> +}
da um enter plz ;-;

2019-10-09 13:41 UTC, alysonNBS commented on lib/src/clayblocks/image.dart
Linha em branco entre os imports?

2019-10-09 13:41 UTC, alysonNBS commented on lib/src/clayblocks/image.dart
>  }
Falta quebra de linha

2019-10-09 13:42 UTC, alysonNBS commented on lib/src/clayblocks/audio.dart
>  }
Fim de linha

2019-10-09 13:42 UTC, alysonNBS commented on lib/src/clayblocks/clayblock.dart
> +}
Fim de linha

2019-10-09 13:42 UTC, alysonNBS commented on lib/src/clayblocks/index.dart
>  export './video.dart';
Fim de linha

2019-10-09 13:45 UTC, alysonNBS commented on lib/src/clayblocks/text.dart
> +  final String content;
Organizar melhor esse bloco de código.

2019-10-09 13:45 UTC, alysonNBS commented on lib/src/clayblocks/video.dart
>  }
Fim de linha

2019-10-09 13:46 UTC, alysonNBS commented on lib/src/container.dart
> +}
Fim de linha

2019-10-09 13:46 UTC, alysonNBS commented on lib/taiper.dart
>  export 'src/styling.dart';
Fim de linha

2019-10-09 13:51 UTC, alysonNBS commented on lib/src/clayblocks/text.dart
> +
Duas linhas em branco no final do arquivo

2019-10-15 15:25 UTC, alysonNBS commented on development_app/lib/main.dart
> +      )
virgula ao final

2019-10-15 15:26 UTC, alysonNBS commented on examples/instantiation.dart
> +        TextClayblock(content: "test")
virgula ao final

2019-10-17 14:53 UTC, Jagni commented on lib/src/container.dart
> +
Remover linha em branco

2019-10-17 14:57 UTC, alysonNBS approved these changes

2019-10-21 14:37 UTC, RegisMelgaco approved these changes

2019-10-21 14:37 UTC, merged