ImageClayblock: local asset and web image
Red-Ovenbirds/taipa-builder pull request #27
Opened 2019-10-21 22:06 UTC by alysonNBS

2019-10-24 12:08 UTC, Jagni requested changes

2019-10-24 12:08 UTC, Jagni commented on lib/src/clayblocks/image.dart
> +class _ImageStateful extends StatefulWidget {
Acho desnecessário ter "Stateful" no nome da classe. Chama de ClayImage ou AlgumPrefixoSimplesImage.

2019-10-24 12:08 UTC, Jagni commented on lib/src/clayblocks/image.dart
> +              Size size = snapshot.data;
Se houver erro, exibir para o usuário. Permitir também que ele dê um tap para tentar novamente.

2019-10-24 12:08 UTC, Jagni commented on lib/src/clayblocks/image.dart
> +                  double minConstraints = min(constraints.maxWidth, constraints.maxHeight);
essas variáveis podiam ser renomeadas, talvez parentMinHeight e deviceMinHeight

2019-10-24 12:08 UTC, Jagni commented on lib/src/clayblocks/image.dart
> +enum ImageClayblockType {local, web}
inserir enter no final do arquivo

2019-10-24 12:08 UTC, Jagni commented on lib/src/clayblocks/image.dart
> +          return null;
Coloca num default do switch

2019-10-26 13:29 UTC, RegisMelgaco submitted a review, later dismissed
# Faltam testes

Faz um rebase com a development e cria alguns testes, pra gente ir experimentando e aprendendo a usar

2019-10-26 14:03 UTC, Jagni reviewed
Bem top! Como o Régis falou, tenta só criar alguns testes simples com URLs inválidas.

O que acontece quando uma LocalImage falha, por exemplo? Não faz sentido ter um retry, teria que mostrar algum erro mesmo.

2019-10-26 14:03 UTC, Jagni commented on lib/src/clayblocks/image.dart
> +        return Container(
Acho que merecem ficar em métodos, pro build ficar mais enxuto.
Usa a magia do `ctrl + .` nos Containers e a opção "Extract Method".

Ai teria o `buildLocalImage()` e `buildWebImage()`.

```dart
Widget build(BuildContext context) {
 switch(type) {
  case ImageClayblockType.local:
   return buildLocalImage(context);
  case ImageClayblockType.web:
   return buildWebImage(context);
}
```

2019-11-04 12:18 UTC, Jagni commented
Achei um probleminha de UI com o iOS: não tem botão de voltar/fechar.

Só tá dando pra sair dando um EdgePan (scrollando bem da pontinha da tela). É um padrão do iOS mas ele é sempre usado com a alternativa do botão também.

Vê se essa biblioteca tem alguma opção de saída com botão ou com scroll vertical e habilita por padrão.

2019-11-13 14:05 UTC, Jagni approved these changes

2019-11-21 15:37 UTC, merged