fix text-ref layout #29
Red-Ovenbirds/taipa-builder pull request #32
Opened 2019-10-23 20:04 UTC by RegisMelgaco

fix #29

2019-10-24 11:56 UTC, Jagni commented
Isso dá um bom caso de teste!

2019-10-24 21:53 UTC, Jagni requested changes
Show! Só renomear pra ULItem. E a tag também, pra text/ulitem.

2019-10-26 12:48 UTC, Jagni requested changes

2019-10-26 12:48 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +    final messenge = "My messenge";
O correto é "message"

2019-10-26 12:48 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +    expect(find.text(value2), findsOneWidget);
Incluir caso de teste com types inválidos e vazios.
Incluir caso de teste para verificar se o theme correto tá sendo aplicado em text/title e text/body.

2019-10-26 12:48 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +    ));
Acho que o Builder e o Container devem ficar em arquivos de teste diferentes e com outros casos.

2019-10-26 12:48 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +    ));
E acho que o builder só deveria ter unit tests (checando se tá instanciando corretamente, se tá ignorando quando os dados tão errados, etc.).

Já o Container só widget tests (se os styles estão corretos, se os texts estão sendo exibidos, etc.)

2019-10-26 13:08 UTC, RegisMelgaco commented on test/src/clayblocks/text_test.dart
> +    expect(find.text(value2), findsOneWidget);
> Incluir caso de teste com types inválidos e vazios.

Esse teste ele não tá passando, eu faço o teste e arrumo? É que tem a outra branch :/

2019-10-26 13:08 UTC, RegisMelgaco commented on test/src/clayblocks/text_test.dart
> +    expect(find.text(value2), findsOneWidget);
> Incluir caso de teste para verificar se o theme correto tá sendo aplicado em text/title e text/body.

Como testa?

2019-10-26 13:09 UTC, RegisMelgaco commented on test/src/clayblocks/text_test.dart
> +    ));
> Acho que o Builder e o Container devem ficar em arquivos de teste diferentes e com outros casos.

Concordo

2019-10-26 13:12 UTC, RegisMelgaco commented on test/src/clayblocks/text_test.dart
> +    ));
> E acho que o builder só deveria ter unit tests (checando se tá instanciando corretamente, se tá ignorando quando os dados tão errados, etc.).

Acho que o teste de widget faz bem essa função. Pode explicar melhor a diferença e vantagens

2019-10-26 13:14 UTC, RegisMelgaco commented on test/src/clayblocks/text_test.dart
> +    ));
> Já o Container widget tests e de integração (se os clayblocks esperados estão sendo exibidos, verificar theme do container, scroll correto, overflows etc.)

Posso estudar pra fazer esses testes. Só tenho um pouco de receio de a gente deixar o teste um pouco amarrado demais, tipo a gente não poder alterar o estilo e ele já ir quebrando.

2019-10-26 13:17 UTC, RegisMelgaco commented on test/src/clayblocks/text_test.dart
> +    expect(find.text(value2), findsOneWidget);
> > Incluir caso de teste com types inválidos e vazios.
> 
> Esse teste ele não tá passando, eu faço o teste e arrumo? É que tem a outra branch :/

Que tal eu dar rebase da outra branch com essa pra arrumar isso lá?

2019-10-26 13:45 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +    ));
> > E acho que o builder só deveria ter unit tests (checando se tá instanciando corretamente, se tá ignorando quando os dados tão errados, etc.).
> 
> Acho que o teste de widget faz bem essa função. Pode explicar melhor a diferença e vantagens

É que exibir o widget não faz parte do escopo do Builder, então não deve ser testado por ele. Se ele gera um Clayblock da forma correta essa instância vai ser "coberta" pelos outros testes que já foram definidos especificamente pra classe dessa instância.

Acho que fica até melhor assim: nos Clayblocks os testes de widget individuais e o Container cuide só dos de integração e testes de widget somente do Container.

Por agora os testes de style tem que ser amarrados mesmo. Quando a gente introduzir a lógica do TaipaTheme e customização vamos precisar reescrever.

2019-10-26 20:09 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +    expect(find.text(value2), findsOneWidget);
Ahh verdade, é no outro branch. Então aqui só remove esse caso de teste.

Ao invés de dar rebase faz assim: lá no outro branch tu cria o arquivo de teste do Builder e inclui tanto esse que tu tinha feito aqui quanto o que comentei dos types inválidos e vazios.

2019-10-26 20:28 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +    expect(find.text(value2), findsOneWidget);
> Como testa?

O find.text(algumaString) te retorna um Widget do tipo Text.

Ai é só dar uma olhada na propriedade style dele. Não tenho certeza, mas talvez seja só isso:
```dart
foundText.style == TextTheme().title
```
Se não teria que olhar cada uma das propriedades de style e comparar com o Theme 😢
O TextTheme() retorna o tema default do Material pra tipografia preta.

No futuro teria que comparar com o Theme.of(context).textTheme.
Problema: o ambiente de testes não tem context. Se precisar usar o Alyson contornou isso nos testes dele, ele criou um método pumpWidgetWithMaterial. Só não lembro em qual branch

2019-11-13 13:15 UTC, Jagni requested changes

2019-11-13 13:15 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +  test("ClayblockData", () {
Esse teste é util de alguma forma?
Anyway, acho que ele deveria ir pra um clayblock_data_test.dart

2019-11-13 13:15 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +  testWidgets("TaipaBuilder", (WidgetTester tester) async {
Acho que deveria ir para taipa_builder_test.dart

2019-11-13 13:15 UTC, Jagni commented on test/src/clayblocks/text_test.dart
> +  testWidgets("TaiperContainer", (WidgetTester tester) async {
Acho que deveria ir pra taiper_container_test.dart

2019-11-13 19:09 UTC, Jagni approved these changes

2019-11-13 19:09 UTC, merged